rule bwa_mem2_index:
    input:
        "{genome}",
    output:
        "out/{genome}.0123",
        "out/{genome}.amb",
        "out/{genome}.ann",
        "out/{genome}.bwt.2bit.64",
        "out/{genome}.pac",
    log:
        "logs/bwa-mem2_index/{genome}.log",
    params:
        prefix=lambda w: w.genome,
    wrapper:
        "master/bio/bwa-mem2/index"
